CREATE TABLE MATCH(
  ID INT AUTO_INCREMENT,
  FIRST_PLAYER_ID INT,
  SECOND_PLAYER_ID INT,
  WINNER_ID INT,
  NUMBER_FIRST_PLAYER_GAME_WINS INT,
  NUMBER_SECOND_PLAYER_GAME_WINS INT,
  MATCH_COMPLETE BOOLEAN
);